name: Actualizar estadísticas de GitHub

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:

  update-stats:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Obtener estadísticas
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |

          REPOS=$(gh repo list avdevop \
           --limit 100 \
          --json name \
          --jq 'length')
          echo "Repositorios encontrados: $REPOS"
          echo "Lista de repositorios:"

          gh repo list avdevop \
            --limit 100 \
            --json name \
            --jq '.[].name'

          FOLLOWERS=$(gh api users/avdevop \
            --jq '.followers')

          FOLLOWING=$(gh api users/avdevop \
            --jq '.following')

          PUBLIC_REPOS=$(gh api users/avdevop \
            --jq '.public_repos')

          cat > github-stats.json << EOF
          {
            "username": "avdevop",
            "repositories": $REPOS,
            "public_repositories": $PUBLIC_REPOS,
            "followers": $FOLLOWERS,
            "following": $FOLLOWING
          }
          EOF

      - name: Guardar estadísticas

        run: |

          git config user.name "github-actions[bot]"

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add github-stats.json

          git diff --cached --quiet || git commit -m "Actualizar estadísticas de GitHub"

          git push
